/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurante;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author T-204
 */
public class TestResta extends javax.swing.JFrame {

    
    JRadioButton radios[];
    Opcion []opciones;
   
   Pregunta[]preguntas=new Pregunta[2]; 
    int indice;
    
    /**
     * Creates new form TestResta
     */
    public TestResta() {
        initComponents();
        
        setLocationRelativeTo(this);
        siguiente.setEnabled(false);
        
        
        //Generamos en un arreglo los radios button visuales
        radios=new JRadioButton[5];
        opciones=new Opcion[5];
        radios[0]=radioOp1;
        radios[1]=radioOp2;
        radios[2]=radioOp3;
        radios[3]=radioOp4;
        
        
        //Llenamos el modelo con los valores correctos en la interfaz de usuario
        Opcion op1=new Opcion("El Popocatepelt", false);
       //System.out.println("Tu titulo es "+op1.titulo); 
        //System.out.println("Es correcta" +op1.correcta);  
       
        Opcion op2=new Opcion("El Everest", true);
        Opcion op3=new Opcion("El Aconcagua", false);
        Opcion op4=new Opcion("El Pico de Orizaba", false);
           
           
           
           //Se crean los arreglos asi, los []van primero. 
            opciones[0]=op1;
            opciones[1]=op2;
            opciones[2]=op3;
            opciones[3]=op4;
            
           
           //Para hacer la pregunta, "Primero es de tipo String", el segundo de Tipo Arreglo.
           preguntas[0]=new Pregunta("¿Cual es la montaña más alta del mundo",opciones);
           
       
           
           
            Opcion [] opciones2 = new  Opcion [ 4 ];
            //etiquetaTitulo.setText("Todos los siguientes estados tienen costas excepto");
        Opcion op21=new Opcion("Jalisco", false);
       
        Opcion op22=new Opcion("Micoacan ", false);
        Opcion op23=new Opcion("Coahula", true);
        Opcion op24=new Opcion("Tamaulipas", false);
        
        preguntas[1]=new Pregunta("Todos tienen costas exepto ",opciones2);
           
         etiquetaTitulo.setText(preguntas[indice].preg);
        for(int i=0;i<radios.length;i++){
            radios[i].setText(preguntas[indice].opciones[i].titulo);
        }
           
           etiquetaTitulo.setText(preguntas[indice].preg);
        for(int i=0;i<radios.length;i++){
            radios[i].setText(preguntas[indice].opciones[i].titulo);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        radioOp1 = new javax.swing.JRadioButton();
        radioOp2 = new javax.swing.JRadioButton();
        radioOp3 = new javax.swing.JRadioButton();
        radioOp4 = new javax.swing.JRadioButton();
        checar = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTitulo.setText("jLabel1");

        buttonGroup1.add(radioOp1);
        radioOp1.setText("jRadioButton1");

        buttonGroup1.add(radioOp2);
        radioOp2.setText("jRadioButton2");

        buttonGroup1.add(radioOp3);
        radioOp3.setText("jRadioButton3");

        buttonGroup1.add(radioOp4);
        radioOp4.setText("jRadioButton4");

        checar.setText("Checar");
        checar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checarActionPerformed(evt);
            }
        });

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checar)
                            .addComponent(radioOp2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(siguiente))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(etiquetaTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(radioOp1)
                            .addGap(57, 57, 57)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(radioOp4)
                                .addComponent(radioOp3)))))
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(etiquetaTitulo)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioOp1)
                    .addComponent(radioOp3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioOp2)
                    .addComponent(radioOp4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checar)
                    .addComponent(siguiente))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checarActionPerformed
        // TODO add your handling code here:
        
        int indiceSeleccionado=0;
        for(int i=0;i<radios.length;i++){
            if(radios[i].isSelected()){
                indiceSeleccionado=i;
                break;
               
            }
        }
        
       
      JOptionPane.showConfirmDialog(this,""+evaluar(preguntas[indice],indiceSeleccionado));
      indice++;
      
      
        checar.setEnabled(false);
        siguiente.setEnabled(true);
    }//GEN-LAST:event_checarActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
            /*    etiquetaTitulo.setText("Todos los siguientes estados tienen costas excepto");
        Opcion op1=new Opcion("El Popocatepelt", false);
       //System.out.println("Tu titulo es "+op1.titulo); 
        //System.out.println("Es correcta" +op1.correcta);  
       
        Opcion op2=new Opcion("El Everest", true);
        Opcion op3=new Opcion("El Aconcagua", false);
        Opcion op4=new Opcion("El Pico de Orizaba", false);
        
        p2=new Pregunta("¿Cual es la montaña más alta del mundo",opciones);
           
           etiquetaTitulo.setText(p2.preg);
        for(int i=0;i<radios.length;i++){
            radios[i].setText(p2.opciones[i].titulo);
        }*/
        
               etiquetaTitulo.setText(preguntas[indice].preg);
        for(int i=0;i<radios.length;i++){
            radios[i].setText(preguntas[indice].opciones[i].titulo);
        }
            
            siguiente.setEnabled(false);
        checar.setEnabled(true);
        
    }//GEN-LAST:event_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestResta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestResta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestResta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestResta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestResta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checar;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioOp1;
    private javax.swing.JRadioButton radioOp2;
    private javax.swing.JRadioButton radioOp3;
    private javax.swing.JRadioButton radioOp4;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables

public boolean evaluar(Pregunta p, int indiceSeleccionado){
boolean correcta=false;
if(p.opciones[indiceSeleccionado].correcta){
    correcta=true;
    
 }

return correcta;
}
}
